Got it. With the core interactive loop and high-fidelity schedule complete, the final step is to build out the remaining views and provide a way to review the data generated by the prototype. This PRD focuses on creating the "History" view and populating the placeholder pages, effectively completing the prototype's feature set.

---

## PRD-07: History View & Finalizing App Shell

### 1. Overview

This document specifies the requirements for the final phase of the prototype development, which focuses on data review and completing the application's navigational shell. The primary initiative is to build a functional "History" view that allows a user to see a chronological list of all completed and supplemental checks. This provides the crucial "closing of the loop," demonstrating that the actions performed in the prototype are recorded and reviewable. This phase also includes creating polished placeholder content for any remaining, out-of-scope views to ensure the entire application feels complete and navigable.

### 2. Problem & Goals

**Problem:** The application currently has no mechanism for reviewing past activity. Checks that are marked "complete" or created as "supplemental" effectively disappear from the user's view. This makes it impossible to demonstrate the full data lifecycle. Additionally, some primary navigation tabs (like "Dashboard" in some layouts) lead to placeholder content, creating a disjointed user experience.

**Goals:**

1.  **Build the History View:** Create a new view that displays a chronological, filterable list of all non-pending safety checks.
2.  **Implement Basic Filtering:** Provide simple controls within the History view to filter the list by check status (e.g., show only Late/Missed checks).
3.  **Create Polished Placeholders:** Replace all generic "div" placeholders in the application with high-fidelity, full-screen placeholder components that clearly communicate the purpose of the view and its status in the prototype.
4.  **Complete the Navigational Experience:** Ensure every button in the main navigation leads to a visually complete and well-designed screen, making the entire prototype feel cohesive and professional.

### 3. Scope & Key Initiatives

**In Scope:**

*   **`HistoryView` Component:** A new feature view that displays a virtualized list of past checks.
*   **`HistoryCard` Component:** A new component, similar to `CheckCard`, but designed to display historical data (e.g., who performed the check, exact completion time, notes).
*   **Filtering Controls:** A `ToggleGroup` or similar component in the `HistoryView` header to filter the list.
*   **State Management:**
    *   A new `historyFilterAtom` to manage the current filter selection.
    *   A new derived `filteredHistoryAtom` to compute the list of checks to be displayed.
*   **`FullScreenPlaceholder` Component:** A new generic, reusable component for creating polished placeholder screens.
*   **View Population:** The "Dashboard" and any other placeholder views will be populated with this new component.

**Out of Scope:**

*   **Detailed Audit Trail:** The history view will not show a deep, field-by-field audit log. It will be a summary list.
*   **Date Range Filtering:** Filtering will be limited to status only. There will be no complex date pickers or range selectors.
*   **Data Export:** The "Export to PDF/Excel" functionality from the main PRD is not in scope for the prototype.
*   **Backend Data:** All history data is drawn from the same local, in-memory Jotai store.

### 4. UX/UI Specification & Wireframes

This phase focuses on information display and creating a polished "end state" for the prototype.

*   **`HistoryView` Layout:** A standard list view with a header containing filter controls.

    **ASCII Wireframe: `HistoryView.tsx`**
    ```
          +----------------------------------+
          | ≡  History                       |  <-- Header
          |----------------------------------|
          |  [ All ] [ Late/Missed ] [ Supp ]|  <-- ToggleGroup for filtering
          |----------------------------------|
          |                                  |
          | +------------------------------+ |
          | | Room 101 - Completed         | | <-- HistoryCard component
          | | 12:13 PM by Demo User        | |
          | +------------------------------+ |
          |                                  |
          | +------------------------------+ |
          | | Room 104 - Supplemental      | |
          | | 12:04 PM by Demo User        | |
          | +------------------------------+ |
          |                                  |
          +----------------------------------+
    ```

*   **`FullScreenPlaceholder` Component:** A generic, centered message card.

    **ASCII Wireframe: `FullScreenPlaceholder.tsx`**
    ```
          +----------------------------------+
          |                                  |
          |                                  |
          |       +--------------------+     |
          |       |        [ icon ]    |     |
          |       |                    |     |
          |       |    View Title      |     |
          |       |                    |     |
          |       |   Brief message    |     |
          |       |  explaining this   |     |
          |       |   view's purpose.  |     |
          |       +--------------------+     |
          |                                  |
          |                                  |
          +----------------------------------+
          Wrapper BG: var(--surface-bg-secondary)
          Card BG: var(--surface-bg-primary)
    ```

### 5. Architecture & Implementation Plan

1.  **State Management (Jotai):**
    *   In `src/data/atoms.ts`, create the filter atom:
        ```typescript
        export type HistoryFilter = 'all' | 'lateOrMissed' | 'supplemental';
        export const historyFilterAtom = atom<HistoryFilter>('all');
        ```
    *   In `src/data/appDataAtoms.ts`, create the derived atom for the history list:
        ```typescript
        export const filteredHistoryAtom = atom((get) => {
          const allChecks = get(safetyChecksAtom);
          const filter = get(historyFilterAtom);
          const historicalChecks = allChecks.filter(c => c.status !== 'pending');
          // Apply filter logic and sort by date descending
          // ...
          return sortedAndFilteredChecks;
        });
        ```

2.  **Component Implementation:**
    *   **Create `HistoryView.tsx`:**
        *   Create a new directory `src/features/History/`.
        *   The component will use `useAtomValue(filteredHistoryAtom)` to get its data.
        *   It will use `react-virtuoso` to render the list of `HistoryCard` components for performance.
        *   The header will contain an `IconToggleGroup` component that writes to the `historyFilterAtom`.
    *   **Create `HistoryCard.tsx`:**
        *   This component will be similar to `CheckCard` but styled for displaying completed information. It will receive a single `check` object as a prop.
    *   **Create `FullScreenPlaceholder.tsx`:**
        *   Create a new generic component in `src/components/`.
        *   It will accept `icon`, `title`, and `message` as props.
        *   It will use the existing CSS module `FullScreenPlaceholder.module.css`.
    *   **Update Placeholder Views:**
        *   Modify `DashboardView.tsx` (or any other view that is a placeholder in certain layouts) to use the new `FullScreenPlaceholder` component, providing it with relevant content (e.g., icon: 'dashboard', title: 'Dashboard', message: 'This view provides an at-a-glance summary of facility status. Not implemented in this prototype.').
        *   Ensure any other empty views reachable via the `NavBar` are also populated with this component.

### 6. File Manifest

*   **src/features/History/ `[NEW DIRECTORY]`**
    *   `HistoryView.tsx` `[NEW]`
    *   `HistoryView.module.css` `[NEW]`
    *   `HistoryCard.tsx` `[NEW]`
    *   `HistoryCard.module.css` `[NEW]`
*   **src/components/**
    *   `FullScreenPlaceholder.tsx` `[MODIFIED]` (File exists, but implementation is new)
    *   `FullScreenPlaceholder.module.css` `[MODIFIED]` (File exists, but implementation is new)
    *   `IconToggleGroup.tsx` `[REFERENCE]`
*   **src/features/Dashboard/**
    *   `DashboardView.tsx` `[MODIFIED]` (May be updated to use the placeholder)
*   **src/data/**
    *   `atoms.ts` `[MODIFIED]` (Add `historyFilterAtom`)
    *   `appDataAtoms.ts` `[MODIFIED]` (Add `filteredHistoryAtom`)
*   **src/**
    *   `AppShell.tsx` `[MODIFIED]` (Ensure the `HistoryView` is correctly routed and rendered)

### 7. Unintended Consequences Check

*   **Data Consistency:** The `HistoryView` directly depends on the main `safetyChecksAtom`. Any bugs in the state update logic from PRD-04/06 (e.g., incorrectly marking a check as complete) will be immediately visible here. This is actually a benefit, as the `HistoryView` acts as a valuable debugging tool.
*   **Component Reuse:** The `FullScreenPlaceholder` is designed to be generic. We must ensure its styling is simple and robust enough to look good in any content area without causing layout issues.

### 8. Risks & Mitigations

1.  **Risk:** The filtering logic in the derived Jotai atom could become complex and slow if more filters are added.
    *   **Mitigation:** For the defined scope (3 simple filters), the logic will be trivial and performant. We will use standard JavaScript array methods (`.filter()`, `.sort()`) which are highly optimized. This risk is negligible for the prototype.
2.  **Risk:** The `HistoryView` could feel disconnected from the main schedule.
    *   **Mitigation:** We will use consistent typography, spacing tokens, and component styles (`HistoryCard` will share a visual language with `CheckCard`) to ensure a cohesive look and feel across the application.

### 9. Definition of Done

*   [ ] The "History" tab in the main navigation now loads the `HistoryView`.
*   [ ] The `HistoryView` displays a chronological, scrollable list of all completed, late, missed, and supplemental checks.
*   [ ] The list is virtualized using `react-virtuoso`.
*   [ ] Filter controls are present and functional, allowing the user to narrow the list by status.
*   [ ] A new reusable `FullScreenPlaceholder` component has been created.
*   [ ] All previously empty or placeholder views in the application are now populated with the `FullScreenPlaceholder` component, featuring relevant content.
*   [ ] The entire application is navigable without encountering any unstyled or empty pages.